### ISSUE TITLE
omit refunded = true from balance

### ISSUE THREAD

**Issue by dlugo06** [naranhoe/good-admissions#33]
refunded is in stripes table. Count all payments against balance unless it was refunded.

**Comment by naranhoe** [comment]
When "Refunded" BECOMES true for a stripe payment then the balance of the student should increase by the amount of the stripe payment.

-Before_create in the stripe model, check if REFUNDED equals true if so balance would be unaffected.
-In the stripe controller for the update action, check if stripe_params[:refunded] true & @stripe.refunded = false then increase the balance of the @stripe.student.balance by @stripe.amount
-@stripe.student.save after balance has been changed
